util.AddNetworkString("OWTA_blink")
util.AddNetworkString("OWTA_recall")
util.AddNetworkString("OWTA_throwBomb")
util.AddNetworkString("blip")
util.AddNetworkString("OWTA_conVarChanged")
util.AddNetworkString("OWTA_replicateConVars")
